# permissions for end users to edit cloudstorages.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: cloudstorage-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: oadp-operator
    app.kubernetes.io/part-of: oadp-operator
    app.kubernetes.io/managed-by: kustomize
  name: cloudstorage-editor-role
rules:
- apiGroups:
  - oadp.openshift.io
  resources:
  - cloudstorages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - oadp.openshift.io
  resources:
  - cloudstorages/status
  verbs:
  - get
